---
apiVersion: v1
kind: Service
metadata:
  name: todofrontend
  labels:
    app: todo
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
  selector:
    app: todo
    tier: frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todofrontend
  labels:
    app: todo
    tier: frontend

spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo
      tier: frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate

  template:   # pod definition
    metadata:
      labels:
        app: todo
        tier: frontend
    spec:
      containers:
        - name: todofrontend
          image: todofrontend:4.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      #dnsPolicy: ClusterFirst
      #restartPolicy: Always